/**
 * Module Description
 * 
 * Version    Date            Author           Remarks
 * 1.00       25 Feb 2016     WORK-rehanlakhani
 *
 */

/**
 * @param {String} type Context Types: scheduled, ondemand, userinterface, aborted, skipped
 * @returns {Void}
 */


function scheduled(type) 
{
	var rIndex = 0;
	var rMax = 1000;
	var resultSet;
	var counter = 1;
	var csvBody = '';
	
	var customerStatus = ["13","21","31","23","25","24","7","10","8","20","11","14","22","32"];
	
	var searchFilter = [
	                    	new nlobjSearchFilter('status', null, 'anyOf', null, customerStatus),
	                    	new nlobjSearchFilter('isdefaultbilling', null, 'is', null, 'T'),
	                    	new nlobjSearchFilter('isdefaultshipping', null, 'is', null, 'T'),
	                    	new nlobjSearchFilter('isinactive', null, 'is', null, 'F')
	                    ];
	
	var searchColumn = [
	                    	new nlobjSearchColumn('internalid', null, 'GROUP'), // NetSuite Record ID, ISDC External ID - Linked records via ID's generated by systems. 
		                    new nlobjSearchColumn('entitystatus', null, 'GROUP'), //Lead Status 
		                    new nlobjSearchColumn('companyname', null, 'GROUP'), // Company Name 
		                    new nlobjSearchColumn('phone', null, 'GROUP'), // Phone Number 
		                    new nlobjSearchColumn('url', null, 'GROUP'), // Website 
		                    new nlobjSearchColumn('email', null, 'GROUP'), // Email
		                    new nlobjSearchColumn('address1', null, 'GROUP'), // Address1 
		                    new nlobjSearchColumn('address2', null, 'GROUP'), // Address2 
		                    new nlobjSearchColumn('city', null, 'GROUP'), // City 
		                    new nlobjSearchColumn('state', null, 'GROUP'), // State 
		                    new nlobjSearchColumn('zipcode', null, 'GROUP'), // Zip 
		                    new nlobjSearchColumn('country', null, 'GROUP'), // Country
		                    new nlobjSearchColumn('custentity_wrok_w_channel_partner', null, 'GROUP'), //Working with Channel Partner? 
		                    new nlobjSearchColumn('partner', null, 'GROUP'), // Channel Partner 
		                    new nlobjSearchColumn('custentitylead_type', null, 'GROUP'), // Lead Type 
		                    new nlobjSearchColumn('custentity_easi_pulbic_company', null, 'GROUP'), //Public Company 
		                    new nlobjSearchColumn('custentity_ipo_date', null, 'GROUP'), // IPO Date 
		                    new nlobjSearchColumn('custentity_easi_annual_revenue', null, 'SUM'), //Annual Revenue 
		                    new nlobjSearchColumn('custentity_easi_employee_count', null, 'COUNT'), // Number of Employees 
		                    new nlobjSearchColumn('custentity_easi_ticker_symbol', null, 'GROUP'), //Ticker Symbol 
		                    new nlobjSearchColumn('custentity_rivet_recent_sec_filings', null, 'GROUP'), // Recent SEC Filing 
		                    new nlobjSearchColumn('custentity_rivet_xbrl_vendor', null, 'GROUP'), // XBRL Vendor 
		                    new nlobjSearchColumn('custentity_rivet_filing_agent', null, 'GROUP'), //Filing Agent 
		                    new nlobjSearchColumn('custentity_easi_industry', null, 'GROUP'), // Industry 
		                    new nlobjSearchColumn('custentity_broker', null, 'GROUP'), // Broker 
		                    new nlobjSearchColumn('custentity_adx_partnerpillar', null, 'GROUP'), //Channel Partner Pillar 
		                    new nlobjSearchColumn('datecreated','opportunity', 'MAX'), // Date Created (opportunity) 
		                    new nlobjSearchColumn('custentity_date_lsa', null, 'GROUP'), // Last Sales Activity 
		                    new nlobjSearchColumn('custentityrelationship_manager', null, 'GROUP'), //CRM 
		                    new nlobjSearchColumn('custentity_easi_term_risk_status', null, 'GROUP'), //Termination Risk Status 
	                    	new nlobjSearchColumn('custentity_referenceable_client', null, 'GROUP'), // Turnaround Status 
	                    	new nlobjSearchColumn('custentity_legacy_system', null, 'GROUP'), // Equity Legacy System 
	                    	new nlobjSearchColumn('closedate','opportunity', 'MAX') // Close Date (opportunity) 	
	                    ];
	var csvHeader  = '"Owner","Company Name","ExternalID","Lead Status","Lead Type","Email","Phone","Website","NetSuite link",';
		csvHeader += '"Billing Address","Billing City","Billing State","Billing Zip/Postal Code","Billing Country","NetSuite Industry","Working with Channel Partner?",';
		csvHeader += '"Channel Partner","Annual Revenue","Employees","Public Company?","Ticker Symbol","IPO Date","Recent SEC Filing","Filing Agent","XBRL Vendor","Broker","Channel Partner Pillar","CRM","Termination Risk Status","Turnaround Status","Opportunity Created Date","Last Sales Activity","Closed/Sell Date","Equity Legacy System"\n';
	var search = nlapiCreateSearch('customer', searchFilter, searchColumn);
	var rs = search.runSearch();
	do
	{
		resultSet = rs.getResults(rIndex, rIndex + rMax);
		for(var i = 0; i<resultSet.length; i+=1)
		{
			csvBody +=  '"Audaxium Audaxium",' +//1
						'"' + resultSet[i].getValue('companyname', null, 'GROUP') + '",' +//2
						'"' + resultSet[i].getValue('internalid', null, 'GROUP') + '",' +//3
						'"' + resultSet[i].getText('entitystatus', null, 'GROUP') + '",' +//4
						'"' + resultSet[i].getText('custentitylead_type', null, 'GROUP') + '",' +//5
						'"' + resultSet[i].getValue('email', null, 'GROUP') + '",' +//6
						'"' + resultSet[i].getValue('phone', null, 'GROUP') + '",' +//7
						'"' + resultSet[i].getValue('url', null, 'GROUP') + '",' +//8
						'"https://system.netsuite.com/app/common/entity/custjob.nl?id=' + resultSet[i].getValue('internalid', null, 'GROUP') + '",' + //9
						'"' + resultSet[i].getValue('address1', null, 'GROUP') + '",' + //10
						'"' + resultSet[i].getValue('city', null, 'GROUP') + '",' + //11
						'"' + resultSet[i].getValue('state', null, 'GROUP') + '",' + //12
						'"' + resultSet[i].getValue('zipcode', null, 'GROUP') + '",' + //13
						'"' + resultSet[i].getValue('country', null, 'GROUP') + '",' + //14
						'"' + resultSet[i].getValue('custentity_easi_industry', null, 'GROUP') + '",' + //15
						'"' + resultSet[i].getText('custentity_wrok_w_channel_partner', null, 'GROUP') + '",' + //16
						'"' + resultSet[i].getText('partner', null, 'GROUP') + '",' + //17
						'"' + resultSet[i].getValue('custentity_easi_annual_revenue', null, 'SUM') + '",' + //18
						'"' + resultSet[i].getValue('custentity_easi_employee_count', null, 'COUNT') + '",' + //19
						'"' + resultSet[i].getText('custentity_easi_pulbic_company', null, 'GROUP') + '",' + //20
						'"' + resultSet[i].getValue('custentity_easi_ticker_symbol', null, 'GROUP') + '",' + //21
						'"' + resultSet[i].getValue('custentity_ipo_date', null, 'GROUP') + '",' +  //22
						'"' + resultSet[i].getValue('custentity_rivet_recent_sec_filings', null, 'GROUP') + '",' + //23
						'"' + resultSet[i].getText('custentity_rivet_filing_agent', null, 'GROUP') + '",' + //24
						'"' + resultSet[i].getText('custentity_rivet_xbrl_vendor', null, 'GROUP') + '",' + //25
						'"' + resultSet[i].getText('custentity_broker', null, 'GROUP') + '",' + //26
						'"' + resultSet[i].getText('custentity_adx_partnerpillar', null, 'GROUP') + '",' + //27
						'"' + resultSet[i].getText('custentityrelationship_manager', null, 'GROUP') + '",' + //28
						'"' + resultSet[i].getText('custentity_easi_term_risk_status', null, 'GROUP') + '",' + //29
						'"' + resultSet[i].getText('custentity_referenceable_client', null, 'GROUP') + '",' + //30
						'"' + resultSet[i].getValue('datecreated', 'opportunity', 'MAX') + '",' + //31
						'"' + resultSet[i].getValue('custentity_date_lsa', null, 'GROUP') + '",' + //31
						'"' + resultSet[i].getValue('closedate', 'opportunity', 'MAX') + '",' + //32
						'"' + resultSet[i].getText('custentity_legacy_system', null, 'GROUP') + '"\n'; //33

		}
		var csv = nlapiCreateFile('AccountInformation' + counter + '.csv', 'CSV', csvHeader+csvBody);
			csv.setFolder(-14);
			nlapiSubmitFile(csv);
			counter+=1;
			csvBody = '';
		rIndex = rIndex + rMax;
	}
	while(resultSet.length >= 1000)
}


