var COST_NLAPICOPYRECORD = 20;
var COST_NLAPILOADRECORD = 20;
var COST_NLAPISUBMITRECORD = 20;
var COST_NLAPILOOKUPFIELD = 10;
var COST_NLAPISENDEMAIL = 20;
var COST_NLAPICREATERECORD = 20;
var COST_NLAPISCHEDULESCRIPT = 30;
var COST_NLAPISEARCHRECORD = 20;
var LIMIT_NLAPISEARCHRECORD = 1000;
var COST_NLAPIRESOLVEURL = 10;
var COST_NLAPISUBMITFIELD = 10;

var costToProcessASearchResult = 3 * COST_NLAPILOOKUPFIELD +
			1 * COST_NLAPICOPYRECORD +
			1 * COST_NLAPISUBMITRECORD;
			
var costToFinishExecution = COST_NLAPICREATERECORD + COST_NLAPISUBMITRECORD + COST_NLAPISCHEDULESCRIPT + COST_NLAPISUBMITFIELD;

var costToLookupResultsForTaskParameterRecord = 1 * COST_NLAPISEARCHRECORD + 2* COST_NLAPIRESOLVEURL + 1*COST_NLAPILOADRECORD;

var costToLookupAlreadyProcessed = 1 * COST_NLAPISEARCHRECORD;

var costToProcessTaskParameterRecord =  costToLookupResultsForTaskParameterRecord +
+costToProcessASearchResult+
costToLookupAlreadyProcessed + 	
costToFinishExecution + 
1*COST_NLAPISENDEMAIL;

var RUNONCE_DAILY_HOURLY = 'RUNONCE';		
var THIS_IS_SCHEDULED_VS_UNSCHEDULED = false;
var UNSCHEDULED_SCRIPT_ID = null;
var UNSCHEDULED_SCRIPT_DEPLOYMENT_ID = null;
var SESSION_IDENTIFIER_PARAMETER = 'custscript_session_identifier';


