/**
 * On June 25 2016 - We found that SuiteScript 2.0 does NOT have matching Module
 * for Date related APIs from Suite Script 1.0.
 * nlapiAddDays and nlapiAddMonths is missing.
 * This Custom Date library is an attempt to simulate same behavior for
 * nlapiAddDays and nlapiAddMonths ONLY until NS provides one
 * 
 * Below script is generated by NetSuite on the client side.
 * ONLY parts of the script that are needed to provide functionalities for
 * nlapiAddDays and nlapiAddMonths are placed in this library file
 */
define([],

function() {

	var E = [[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31], [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]];
	
	function p(a, d) 
	{
        (a.setFullYear || a.setYear(d));
        a.setFullYear(d);
    }
	
	function n(a) {
        return a.getFullYear ? a.getFullYear() : a.getYear();
    }
	
	function v(a) {
        return 0 === a % 4 && (0 !== a % 100 || 0 === a % 400);
    }
	
	/**
	 * Same as SuiteScript 1.0.
	 * a = Date Object
	 * b = +/- Integer to add to Months
	 */
	function addMonths(a, d) 
	{
        if (0 != d) {
            var e = n(a)
              , c = a.getDate()
              , b = a.getMonth() + d;
            0 > b ? (b += 1,
            e = e + Math.ceil(b / 12) - 1,
            p(a, e),
            b = 11 + b % 12) : 11 < b && (e += Math.floor(b / 12),
            p(a, e),
            b %= 12,
            29 === c && a.setDate(c));
            e = E[v(e) ? 1 : 0][b];
            c > e && a.setDate(e);
            a.setMonth(b);
        }
        return a;
    }
	
	/**
	 * Same as SuiteScript 1.0.
	 * a = Date Object
	 * b = +/- Integer to add to Days
	 */
    function addDays(a, d) 
    {
        if (!(a instanceof Date))
            return a;
        var e = new Date(a.getTime() + 864E5 * d);
        e.getHours() !== a.getHours() && (0 < a.getHours() && e.getHours() < a.getHours() || 0 === a.getHours() && 23 === e.getHours() ? e.setTime(e.getTime() + 36E5) : e.setTime(e.getTime() - 36E5));
        a.setTime(e.getTime());
        return a;
    }
	
	/**
	 * Below return statement contains list of all functions return.
	 * KEY will be used to call the functions
	 */
    return {
    	'addMonths': addMonths,
    	'addDays': addDays
    };
    
});
